version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - 'dependencies'
      - 'javascript'
      # kodiak `merge.automerge_label`
      - 'automerge'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github_actions'
      # kodiak `merge.automerge_label`
      - 'automerge'
